disabled_rules:
  - file_length
  - force_cast
  - comment_spacing
  - private_over_fileprivate
  - vertical_whitespace
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - multiple_closures_with_trailing_closure
  - force_try
  - syntactic_sugar
  - legacy_constructor
  - legacy_constant
  - todo

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - operator_usage_whitespace

trailing_whitespace:
  ignores_empty_lines: true

identifier_name:
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 80
    error: 130
  validates_start_with_lowercase: warning
  allowed_symbols:
    - _

type_name:
  allowed_symbols:
    - _

line_length:
  warning: 160
  error: 260
  ignores_interpolated_strings: true
  ignores_comments: true
  excluded_lines_patterns:
    - ( )*\".*\"$

large_tuple:
  warning: 5
  error: 10

attributes:
  attributes_with_arguments_always_on_line_above: false
  
operator_usage_whitespace:
  severity: error

custom_rules:
  no_c_style_comment:
    name: "C-Style Comment"
    regex: "(/\\*[\\s\\S]*\\*/)"
    match_kinds:
      - comment
    message: "C-Style comment is not recommended, use '//' instead (Command + / for shortcut)"
    severity: warning
